//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class analiz
    {
        public analiz()
        {
            this.an_fio_doc = new HashSet<an_fio_doc>();
            this.fac_an = new HashSet<fac_an>();
            this.mar_list_an = new HashSet<mar_list_an>();
            this.ob_analiz = new HashSet<ob_analiz>();
            this.pac_an = new HashSet<pac_an>();
            this.priem_an = new HashSet<priem_an>();
            this.prof_an = new HashSet<prof_an>();
        }
    
        public string num_an { get; set; }
        public string name_an { get; set; }
        public string kabinrt { get; set; }
        public Nullable<double> stoimosty { get; set; }
        public string kod_preys { get; set; }
    
        public virtual ICollection<an_fio_doc> an_fio_doc { get; set; }
        public virtual ICollection<fac_an> fac_an { get; set; }
        public virtual ICollection<mar_list_an> mar_list_an { get; set; }
        public virtual ICollection<ob_analiz> ob_analiz { get; set; }
        public virtual ICollection<pac_an> pac_an { get; set; }
        public virtual ICollection<priem_an> priem_an { get; set; }
        public virtual ICollection<prof_an> prof_an { get; set; }
    }
}
