//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor
    {
        public factor()
        {
            this.fac_an = new HashSet<fac_an>();
            this.fac_doc = new HashSet<fac_doc>();
            this.pac_fac = new HashSet<pac_fac>();
        }
    
        public int num_fac { get; set; }
        public string name_fac { get; set; }
        public string kod_prik { get; set; }
        public string prik_83 { get; set; }
    
        public virtual ICollection<fac_an> fac_an { get; set; }
        public virtual ICollection<fac_doc> fac_doc { get; set; }
        public virtual ICollection<pac_fac> pac_fac { get; set; }
    }
}
