//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fio_doctor
    {
        public fio_doctor()
        {
            this.an_fio_doc = new HashSet<an_fio_doc>();
            this.doc_fio_doc = new HashSet<doc_fio_doc>();
            this.mar_list_an = new HashSet<mar_list_an>();
            this.mar_list_doc = new HashSet<mar_list_doc>();
            this.priem_an = new HashSet<priem_an>();
            this.priem = new HashSet<priem>();
        }
    
        public int tab_num { get; set; }
        public string fio_doc { get; set; }
        public Nullable<int> otdel { get; set; }
        public string bool_doc { get; set; }
        public Nullable<int> num_m_s { get; set; }
        public Nullable<double> nak_sum { get; set; }
        public Nullable<double> pr_doc { get; set; }
        public Nullable<double> pr_m_s { get; set; }
        public Nullable<double> an_doc { get; set; }
        public Nullable<double> an_m_s { get; set; }
        public Nullable<double> an_dop { get; set; }
    
        public virtual ICollection<an_fio_doc> an_fio_doc { get; set; }
        public virtual ICollection<doc_fio_doc> doc_fio_doc { get; set; }
        public virtual ICollection<mar_list_an> mar_list_an { get; set; }
        public virtual ICollection<mar_list_doc> mar_list_doc { get; set; }
        public virtual ICollection<priem_an> priem_an { get; set; }
        public virtual ICollection<priem> priem { get; set; }
    }
}
