//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MedExam.Common;
using MedExam.Common.interfaces;

namespace MedExam.Patient.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedExamEntities : DbContext
    {
        public MedExamEntities()
            : base("name=MedExamEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<an_fio_doc> an_fio_doc { get; set; }
        public virtual DbSet<analiz> analiz { get; set; }
        public virtual DbSet<doc_fio_doc> doc_fio_doc { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<fac_an> fac_an { get; set; }
        public virtual DbSet<fac_doc> fac_doc { get; set; }
        public virtual DbSet<factor> factor { get; set; }
        public virtual DbSet<fio_doctor> fio_doctor { get; set; }
        public virtual DbSet<mar_list_an> mar_list_an { get; set; }
        public virtual DbSet<mar_list_doc> mar_list_doc { get; set; }
        public virtual DbSet<ob_analiz> ob_analiz { get; set; }
        public virtual DbSet<ob_doctor> ob_doctor { get; set; }
        public virtual DbSet<organization> organization { get; set; }
        public virtual DbSet<pac_an> pac_an { get; set; }
        public virtual DbSet<pac_doc> pac_doc { get; set; }
        public virtual DbSet<pac_fac> pac_fac { get; set; }
        public virtual DbSet<pacient> pacient { get; set; }
        public virtual DbSet<priem> priem { get; set; }
        public virtual DbSet<priem_an> priem_an { get; set; }
        public virtual DbSet<prof_an> prof_an { get; set; }
        public virtual DbSet<prof_doc> prof_doc { get; set; }
        public virtual DbSet<profess> profess { get; set; }
    }
}
