//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        public organization()
        {
            this.pacient = new HashSet<pacient>();
        }
    
        public int num_org { get; set; }
        public string name_org { get; set; }
        public string inn_org { get; set; }
        public string kpp_org { get; set; }
        public string adr_org { get; set; }
        public string bool_org { get; set; }
        public string okvd { get; set; }
        public string num_dog { get; set; }
        public string fio_zak { get; set; }
        public string fio_zak_k { get; set; }
        public string name_org2 { get; set; }
        public Nullable<System.DateTime> akt_date { get; set; }
        public string akt_num { get; set; }
        public Nullable<double> akt_sum { get; set; }
        public Nullable<double> akt_sum_an { get; set; }
        public Nullable<double> akt_sum_dop { get; set; }
        public Nullable<double> akt_sum_an_dop { get; set; }
    
        public virtual ICollection<pacient> pacient { get; set; }
    }
}
