//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_fac
    {
        public int num_pac { get; set; }
        public int num_fac { get; set; }
        public string name_fac { get; set; }
        public string kod_prik { get; set; }
        public string kod_83 { get; set; }
    
        public virtual factor factor { get; set; }
        public virtual pacient pacient { get; set; }
    }
}
