//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacient
    {
        public pacient()
        {
            this.pac_an = new HashSet<pac_an>();
            this.pac_doc = new HashSet<pac_doc>();
            this.pac_fac = new HashSet<pac_fac>();
            this.priem_an = new HashSet<priem_an>();
            this.priem = new HashSet<priem>();
        }
    
        public int num_pac { get; set; }
        public string fam_pac { get; set; }
        public string io_pac { get; set; }
        public string pol { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> data_birth { get; set; }
        public string polic_ser { get; set; }
        public string polic_nom { get; set; }
        public Nullable<System.DateTime> polic { get; set; }
        public Nullable<System.DateTime> data_kart { get; set; }
        public string platel { get; set; }
        public string rol { get; set; }
        public string zacr { get; set; }
        public int num_m_rab { get; set; }
        public int num_org { get; set; }
        public int num_prof { get; set; }
        public string stag { get; set; }
        public string pech_kart { get; set; }
        public string snils { get; set; }
        public string change_date { get; set; }
        public string fac_is { get; set; }
        public string obyem_is { get; set; }
    
        public virtual organization organization { get; set; }
        public virtual ICollection<pac_an> pac_an { get; set; }
        public virtual ICollection<pac_doc> pac_doc { get; set; }
        public virtual ICollection<pac_fac> pac_fac { get; set; }
        public virtual profess profess { get; set; }
        public virtual ICollection<priem_an> priem_an { get; set; }
        public virtual ICollection<priem> priem { get; set; }
    }
}
