//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedExam.Patient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class profess
    {
        public profess()
        {
            this.pacient = new HashSet<pacient>();
            this.prof_an = new HashSet<prof_an>();
            this.prof_doc = new HashSet<prof_doc>();
        }
    
        public int num_prof { get; set; }
        public string name_prof { get; set; }
    
        public virtual ICollection<pacient> pacient { get; set; }
        public virtual ICollection<prof_an> prof_an { get; set; }
        public virtual ICollection<prof_doc> prof_doc { get; set; }
    }
}
